#!/bin/bash  
g++ -std=c++14 -o runBst -DISBST bstDriver.cpp bst.cpp treap.cpp
echo "Compiled Bst"
g++ -std=c++14 -o runtreap bstDriver.cpp bst.cpp treap.cpp
echo "Compiled Treap"
g++ -std=c++14 -o original original.cpp
echo "compiled Original"